.github/workflows/main.yml
.vscode/c_cpp_properties.json
.vscode/launch.json
packages/emnapi/README.md
packages/emnapi/README_CN.md
packages/emnapi/include/napi-inl.h
packages/emnapi/include/napi.h
packages/emnapi/include/node_api.h
packages/emnapi/include/node_api_types.h
packages/emnapi/src/emnapi.c
packages/emnapi/src/init.ts
packages/emnapi/src/simple-async-operation.ts
packages/emnapi/src/typings/runtime.d.ts
packages/test/async/async.html
packages/test/async/async.test.js
packages/test/async/binding.c
packages/test/cgen.config.js
packages/test/util.js

This PR implement these APIs in node_api.h
- [napi_create_async_work](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_create_async_work)
- [napi_delete_async_work](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_delete_async_work)
- [napi_queue_async_work](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_queue_async_work)
- [napi_cancel_async_work](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_cancel_async_work)
As discussion in emscripten-core/emscripten#17213, current implementation depends Emscripten pthread (`-sUSE_PTHREADS=1`). Also recommand to specifying thread pool size explicitly (`-sPTHREAD_POOL_SIZE=4`).

Support simple asynchronous operations

---

.vscode/c_cpp_properties.json
.vscode/launch.json
packages/emnapi/include/node_api.h
packages/emnapi/include/node_api_types.h
packages/emnapi/src/emnapi.c
packages/emnapi/src/init.ts
packages/emnapi/src/queue.h
packages/emnapi/src/thread-safe-function.ts
packages/emnapi/src/util.ts
packages/runtime/src/typings/common.d.ts
packages/test/cgen.config.js
packages/test/tsfn/binding.c
packages/test/tsfn/tsfn.test.js
script/release.js

This PR implement [asynchronous thread-safe function calls](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#asynchronous-thread-safe-function-calls)
- [napi_create_threadsafe_function](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_create_threadsafe_function) (`async_resource` and `async_resource_name` parameter have no effect)
- [napi_get_threadsafe_function_context](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_get_threadsafe_function_context)
- [napi_call_threadsafe_function](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_call_threadsafe_function)
- [napi_acquire_threadsafe_function](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#napi_acquire_threadsafe_function)
- …

Support asynchronous thread-safe function calls

---

packages/emnapi/CMakeLists.txt
packages/emnapi/README.md
packages/emnapi/include/node_api.h
packages/emnapi/src/emnapi.c
packages/emnapi/src/init.ts
packages/emnapi/src/simple-async-operation.ts
packages/emnapi/src/thread-safe-function.ts
packages/emnapi/src/threadpool.c
packages/test/cgen.config.js
packages/test/pool/binding.c
packages/test/pool/pool.html
packages/test/pool/pool.test.js
packages/test/script/test.js

feat: port libuv threadpool

---

packages/emnapi/include/napi-inl.h
packages/emnapi/include/napi.h
packages/emnapi/include/node_api.h
packages/emnapi/src/value-operation.ts
packages/emnapi/src/value/convert2c.ts
packages/emnapi/src/value/create.ts
packages/runtime/src/Handle.ts
packages/test/buffer/binding.c
packages/test/buffer/buffer.finalizer.test.js
packages/test/buffer/buffer.test.js
packages/test/cgen.config.js
packages/test/script/test.js
packages/test/tick.js

I don't understand the test structure - they seem to be adapted versions of official N-API tests, but without GYP and with some other modifications. Are they converted automatically somehow or do you rewrite them manually?
Also, you might notice that I went the slightly easier path for `napi_create_external_buffer` by simply wrapping `napi_create_external_arraybuffer`. In theory, both should have more or less the same effect, except that array buffer might be reused for other views and so the finalize callback might be called a bit later; that said, finalize callbacks are already not guaranteed to run at specific time (or at all) so this shouldn't be an issue.

Buffer support

---

packages/emnapi/src/init.ts
packages/emnapi/src/typings/runtime.d.ts

fix: init after `__wasm_call_ctors`

---

packages/emnapi/src/error.ts
packages/emnapi/src/function.ts
packages/emnapi/src/internal.ts
packages/emnapi/src/value/convert2napi.ts
packages/emnapi/src/value/create.ts
packages/emnapi/src/wrap.ts
packages/runtime/src/index.ts
packages/runtime/src/util.ts

fix: decode string with specified buffer size

---

packages/emnapi/include/emnapi.h
packages/emnapi/include/node_api.h
packages/emnapi/src/emnapi.ts
packages/emnapi/src/internal.ts
packages/emnapi/src/typings/runtime.d.ts
packages/emnapi/src/value/convert2c.ts
packages/emnapi/src/value/create.ts
packages/runtime/src/typings/napi.d.ts
packages/test/buffer/binding.c
packages/test/cgen.config.js
packages/test/emnapitest/binding.c
packages/test/emnapitest/emnapi.test.js
packages/test/typedarray/binding.c

#16 
There is no way to reset detached `TypedArray.prototype.buffer` to newly growed wasm memory ArrayBuffer.

feat: emnapi_create_memory_view

---

.github/workflows/main.yml
packages/emnapi/README.md
packages/test/CMakeLists.txt
packages/test/script/test.js
script/release.js

[wasi-sdk-20](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20) is available.

prebuild wasm32-wasi-threads libraries

---

.github/workflows/main.yml
packages/test/async_cleanup_hook/binding.c
packages/test/cleanup_hook/binding.c
packages/test/cleanup_hook/cleanup_hook.test.js

https://github.com/nodejs/node/pull/46692

test: verify cleanup hooks order

---

packages/emnapi/include/js_native_api_types.h
packages/emnapi/src/js_native_api.c
packages/emnapi/src/macro.ts
packages/runtime/src/Context.ts
packages/runtime/src/env.ts
packages/runtime/src/typings/napi.d.ts
packages/test/CMakeLists.txt
packages/test/ref/ref_finalizer.test.js
packages/test/ref_by_node_api_version/binding.c
packages/test/runjs/binding.c
packages/test/runjs/entry_point.c
packages/test/runjs/runjs.test.js
packages/test/script/test.js

https://github.com/nodejs/node/pull/47986

add status napi_cannot_run_js

---

packages/emnapi/include/js_native_api.h
packages/emnapi/include/node_api.h
packages/emnapi/src/js_native_api.c
packages/emnapi/src/version.ts
packages/runtime/src/typings/common.d.ts
packages/test/error/binding.c
packages/test/general/general.test.js
packages/test/property/binding.c
packages/test/ref/binding.c

https://github.com/nodejs/node/pull/48151

define version 9

---

packages/emnapi/include/uv.h
packages/emnapi/src/uv/threadpool.c
packages/emnapi/src/uv/unix/thread.c
packages/emnapi/src/uv/uv-common.c
packages/emnapi/src/uv/uv-common.h

Exposing threadpool cleanup from libuv + adding missing API.
While proper cleanup is not critical in Node.js, where exiting process automatically kills all associated threads, it's important for environments like Stackblitz where otherwise spawned Worker will be stuck waiting on a condvar (on an atomic) forever in background even after the Node.js command has finished, leading to Worker leaks.

Expose threadpool cleanup

---

packages/test/CMakeLists.txt
packages/test/script/test.js
packages/test/uv_threadpool_size/binding.c
packages/test/uv_threadpool_size/uv_threadpool_size.test.js

https://github.com/nodejs/node/pull/49165

test: add test for effect of UV_THREADPOOL_SIZE

---

packages/emnapi/src/function.ts
packages/emnapi/src/internal.ts
packages/runtime/src/CallbackInfo.ts
packages/test/CMakeLists.txt
packages/test/cbinfo/binding.c
packages/test/cbinfo/cbinfo.test.js

Previously `napi_callback_info` was always 0, calling `napi_get_cb_info` could only get the JS callback information of the function at the top of the call stack.

represent `napi_callback_info` with non-zero number

---

packages/emnapi/src/function.ts

fix: add missing `CHECK_ARG(env, cbinfo);`

---

packages/emnapi/src/value/convert2c.ts

fix: wrap `napi_get_array_length` and `napi_get_prototype` with PREAMBLE

---

packages/emnapi/CMakeLists.txt
packages/emnapi/README.md
packages/emnapi/include/emnapi_common.h
packages/emnapi/include/js_native_api.h
packages/emnapi/include/node_api.h
packages/test/CMakeLists.txt

https://github.com/nodejs/node/pull/49037
The update of node-api-headers may not be timely. Keep the built-in header file so that emnapi can respond to changes in Node-API at any time.
Additional suggestion to users:
- Always define `-DBUILDING_NODE_EXTENSION`
- Emscripten users should define `-DNAPI_EXTERN=__attribute__((__import_module__("env")))` manually since `napi` is the default module where Node.js wants to import symbols from. see https://github.com/emscripten-core/emscripten/issues/20035

sync latest headers

---

packages/emnapi/src/async_context.c
packages/emnapi/src/async_work.c
packages/emnapi/src/core/async-work.ts
packages/emnapi/src/emnapi_internal.h
packages/emnapi/src/emscripten/async-work.ts
packages/emnapi/src/error.ts
packages/emnapi/src/function.ts
packages/emnapi/src/life.ts
packages/emnapi/src/macro.ts
packages/emnapi/src/promise.ts
packages/emnapi/src/string.ts
packages/emnapi/src/threadsafe-function.ts
packages/emnapi/src/threadsafe_function.c
packages/emnapi/src/value-operation.ts
packages/emnapi/src/value/convert2c.ts
packages/emnapi/src/value/convert2napi.ts
packages/emnapi/src/value/create.ts
packages/emnapi/src/value/global.ts
packages/emnapi/src/wrap.ts
packages/emnapi/transformer/src/macro.ts

https://github.com/nodejs/node/pull/50664

factor out common code into macros

---

packages/ts-transform-emscripten-parse-tools/src/index.ts

If `window.SharedArrayBuffer === undefined`, we can use
```js
Object.prototype.toString.call(maybeSAB.constructor) === '[object SharedArrayBuffer]'
```
to determine whether an object is a `SharedArrayBuffer`.

fix: improve `getUnsharedTextDecoderView`

---

package.json

a `prepare` script is a nice to have addition, it is run automatically whenever the package is installed
it allows to install dev versions directly from github and to use `npm link` locally

feat: add a prepare script

---

packages/emnapi/src/value/convert2c.ts
packages/test/buffer/binding.c
packages/test/buffer/buffer.test.js

https://github.com/nodejs/node/pull/51571

test: make napi_get_buffer_info check if passed buffer is valid

---

packages/emnapi/include/node/js_native_api.h
packages/emnapi/include/node/js_native_api_types.h
packages/emnapi/include/node/node_api.h
packages/emnapi/src/emnapi_internal.h
packages/test/common.h
packages/test/finalizer/binding.c
packages/test/ref_by_node_api_version/binding.c
packages/test/runjs/binding.c
packages/test/string/binding.c
packages/test/util.js

- https://github.com/nodejs/node/pull/50060
- https://github.com/nodejs/node/pull/51801

feat: segregate nogc APIs from rest via type system

---

packages/emnapi/README.md
packages/emnapi/common.gypi
packages/emnapi/emnapi.gyp

- https://github.com/nodejs/gyp-next/pull/222
- https://github.com/nodejs/gyp-next/pull/240

feat: gyp add OS `wasm` alias

---

packages/core/src/emnapi/index.d.ts
packages/core/src/worker.ts
packages/emnapi/src/core/init.ts
packages/emnapi/src/core/scope.d.ts
packages/test/util.js

https://github.com/WebAssembly/wasi-threads?tab=readme-ov-file#design-choice-pthreads
> 4. in pthread_create, call wasi_thread_spawn with the configured start_args and use atomic.wait to wait for the start_args->thread->tid value to change (note that for web polyfills this may not be necessary since creation of web workers is not synchronous)
Not available on browser.

feat: add new option to allow waiting thread start before thread-spawn return

---

packages/core/src/emnapi/index.d.ts
packages/core/src/load.ts
packages/emnapi/README.md
packages/emnapi/src/core/index.ts
packages/emnapi/src/core/init.ts
packages/emnapi/src/core/scope.d.ts
packages/test/util.js
packages/wasi-threads/README.md
packages/wasi-threads/src/index.ts
packages/wasi-threads/src/thread-manager.ts
packages/wasi-threads/src/util.ts
packages/wasi-threads/src/wasi-threads.ts

https://emscripten.org/docs/tools_reference/settings_reference.html#pthread-pool-size
```js
instantiateNapiModule({
/**
* equivalent to { size: 0, strict: false }
*/
reuseWorker: true,
reuseWorker: {
size: 4, // equivalent to emscripten's PTHREAD_POOL_SIZE
strict: true // equivalent to emscripten's PTHREAD_POOL_SIZE_STRICT=2
}
})
```
If `size > 0`, only asynchronous loading API (`instantiateNapiModule` / `loadNapiModule`) can guarantee thread pool ready before emnapi initialization.

feat: `reuseWorker` strict mode

---

packages/emnapi/include/node/js_native_api.h
packages/emnapi/src/value/convert2napi.ts
packages/test/string/binding.c
packages/test/string/test.js

https://github.com/nodejs/node/pull/52984

add support for UTF-8 and Latin-1 property keys

---

packages/runtime/src/Context.ts

Deno/Web MessageChannel does not support ref and unref as node does. A simple check if the function actually exists will probably fix some issues folks are having trying to utilize this in other modern runtimes. 
https://github.com/lovell/sharp/issues/3912#issuecomment-1866261154
https://developer.mozilla.org/en-US/docs/Web/API/MessagePort
https://nodejs.org/api/worker_threads.html#portref

add checks for message channel usage in web runtime

---

.github/workflows/main.yml
packages/core/src/worker.ts
packages/emnapi/CMakeLists.txt
packages/emnapi/README.md
packages/emnapi/common.gypi
packages/emnapi/emnapi.gyp
packages/emnapi/src/core/async.ts
packages/emnapi/src/core/init.ts
packages/emnapi/src/emnapi_internal.h
packages/emnapi/src/emscripten/init.ts
packages/emnapi/src/util.ts
packages/emnapi/src/wasi_wait.c
packages/runtime/src/Context.ts
packages/runtime/src/FunctionTemplate.ts
packages/test/CMakeLists.txt
packages/test/async/main.js
packages/test/cleanup_hook/cleanup_hook.test.js
packages/test/exception/exception.finalizer.test.js
packages/test/finalizer/finalizer_fatal.test.js
packages/test/node-addon-api/error.test.js
packages/test/script/test.js
packages/test/trap_in_thread/binding.c
packages/test/trap_in_thread/trap_in_thread-wasi.html
packages/test/trap_in_thread/trap_in_thread-wasi.js
packages/test/trap_in_thread/trap_in_thread.test.js
packages/test/util.js
packages/test/worker.mjs
packages/wasi-threads/src/command.ts
packages/wasi-threads/src/index.ts
packages/wasi-threads/src/worker.ts

fix #159 
- Requires https://github.com/WebAssembly/wasi-libc/pull/562 (wasi-sdk 26+)
- Requires WASI users to pass `--export=emnapi_thread_crashed` to wasm-ld

fix(wasi): avoid deadlock caused by child thread abort when the main thread is in `Atomics.wait`
