- packages/emnapi/src/simple-async-operation.ts
> fix: read _emnapiAsyncWorkListener of undefined

- packages/emnapi/src/emnapi.c
- packages/emnapi/src/uv/unix/thread.c
- packages/emnapi/src/uv/uv-common.c
- packages/test/cgen.config.js
> fix: unused variables (#10)

- packages/emnapi/src/internal.ts
- packages/test/function/binding.c
- packages/test/function/function.test.js
> fix `SyntaxError` when using keywords as name

- .eslintrc.js
- packages/emnapi/script/build.js
- packages/emnapi/src/core/async.ts
- packages/emnapi/src/core/init.ts
- packages/emnapi/src/function.ts
- packages/emnapi/src/node.ts
- packages/emnapi/src/threadsafe-function.ts
- packages/emnapi/src/value/create.ts
- packages/runtime/src/typings/napi.d.ts
This is for bare wasm32 and rust, without WASI.
Next I'll create another PR to implement multithreaded version async work via Web Worker in JS. Instantiating related API may need to be changed on non-emscripten.
> Implement TSFN in JS

- packages/emnapi/src/uv/unix/async.c
https://github.com/toyobayashi/emnapi/issues/41#issuecomment-1484660662
> use `emscripten_main_runtime_thread_id` 

- packages/test/object/object.test.js
- packages/test/object/test_object.c
https://github.com/nodejs/node/pull/47141
> test: extend type-tagging to externals

- CONTRIBUTING.md
- packages/emnapi/script/build.js
- packages/emnapi/src/core/async-work.ts
- packages/emnapi/src/core/async.ts
- packages/emnapi/src/emscripten/runtime.d.ts
- packages/emnapi/src/memory.ts
- packages/emnapi/src/threadsafe-function.ts
- packages/emnapi/src/typings/compiler.d.ts
- packages/emnapi/src/value/create.ts
- packages/emnapi/transformer/src/index.ts
https://github.com/emscripten-core/emscripten/pull/19160
> remove `makeMalloc`

- packages/emnapi/include/emnapi_common.h
- packages/emnapi/include/js_native_api.h
- packages/emnapi/include/js_native_api_types.h
- packages/emnapi/include/node_api.h
- packages/emnapi/include/node_api_types.h
include https://github.com/nodejs/node/pull/46319
> Sync Node-API headers from Node.js official repo

- packages/emnapi/src/string.ts
- packages/test/string/binding.c
- packages/test/string/test.js
fix the performance impact introduced by https://github.com/toyobayashi/emnapi/pull/46
> perf: decode small UTF8 string

- packages/emnapi/src/value-operation.ts
- packages/emnapi/src/value/create.ts
- packages/runtime/src/Context.ts
- packages/runtime/src/Handle.ts
- packages/runtime/src/util.ts
- old Node.js has no `MessageChannel` on `globalThis`
- wechat miniprogram environment has no `MessageChannel`
> fix MessageChannel undefined

- packages/emnapi/README.md
- packages/emnapi/include/node_api.h
- packages/emnapi/src/core/init.ts
- packages/emnapi/src/core/miscellaneous.ts
- packages/emnapi/src/emscripten/init.ts
- packages/emnapi/src/emscripten/miscellaneous.ts
- packages/emnapi/src/life.ts
- packages/emnapi/src/miscellaneous.ts
- packages/emnapi/src/node_api.c
- packages/runtime/src/Context.ts
- packages/runtime/src/Persistent.ts
- packages/runtime/src/Reference.ts
- packages/runtime/src/env.ts
- packages/runtime/src/index.ts
- packages/runtime/src/typings/common.d.ts
- packages/runtime/src/util.ts
- packages/test/CMakeLists.txt
- packages/test/ref/ref.test.js
- packages/test/ref_by_node_api_version/binding.c
- packages/test/ref_by_node_api_version/ref_by_node_api_version.test.js
- packages/test/rust/.cargo/config.toml
- packages/test/util.js
Implement https://github.com/nodejs/node/pull/45715, close #61
> get Node API version used by addon

- package.json
- packages/emnapi/src/macro.ts
- packages/emnapi/transformer/src/macro.ts
- packages/runtime/src/util.ts
> allow macros defined in source code

- packages/emnapi/src/value/convert2c.ts
> fix: truncate number in `napi_get_value_{int32,uint32,int64}`

- packages/test/runjs/binding.c
https://github.com/nodejs/node/pull/51898
> test: fix unreliable assumption in js-native-api/test_cannot_run_js

- packages/test/object/test_object.c
https://github.com/nodejs/node/pull/52426
> test: store external type tags by value

- packages/emnapi/include/node/js_native_api.h
- packages/emnapi/include/node/js_native_api_types.h
- packages/emnapi/include/node/node_api.h
- packages/emnapi/src/async_cleanup_hook.c
- packages/emnapi/src/async_work.c
- packages/emnapi/src/emnapi_internal.h
- packages/emnapi/src/js_native_api.c
- packages/emnapi/src/node_api.c
- packages/emnapi/src/threadsafe_function.c
- packages/test/common.h
- packages/test/finalizer/binding.c
- packages/test/ref_by_node_api_version/binding.c
- packages/test/runjs/binding.c
- packages/test/string/binding.c
https://github.com/nodejs/node/pull/53830
> refactor: rename nogc to basic

- packages/emnapi/src/value/convert2c.ts
- packages/runtime/src/Handle.ts
https://github.com/napi-rs/napi-rs/pull/2296
> fix: `napi_is_buffer(Uint8Array)` should return `true`

- packages/emnapi/include/node/node_api.h
https://github.com/nodejs/node/pull/56162
> remove deprecated attribute from napi_module_register

- packages/ts-transform-emscripten-parse-tools/src/index.ts
- packages/wasi-threads/src/util.ts
> fix: check SharedArrayBuffer

- packages/core/package.json
- packages/test/CMakeLists.txt
- packages/test/script/test.js
- packages/test/trap_in_thread/binding.c
- packages/test/trap_in_thread/trap_in_thread.test.js
- packages/wasi-threads/package.json
- packages/wasi-threads/src/wasi-threads.ts
- packages/wasi-threads/src/worker.ts
> fix(wasm32-wasip1-threads): process never exit if trap in threads

- packages/emnapi/include/node/js_native_api.h
https://github.com/nodejs/node/pull/59684
> feat: make napi_delete_reference use node_api_basic_env
